// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ShoulderInputCommonEvents","status":true,"description":"Maps A/W/S/D + controller shoulders (including analog L2/R2) to Common Events.","parameters":{"L1 Common Event":"1","L2 Common Event":"2","R1 Common Event":"3","R2 Common Event":"4"}}
];
